In [18]:
clear all

In [19]:
import pandas as pd
import numpy as np
import bibliothek as bib

In [20]:
df_ue = pd.read_json('Prepro/ue_data_051222.json')

In [21]:
df2 = pd.read_json("Prepro/cell_data.txt")

In [22]:
cells=df2['cell']
cell_list=np.array([])
for i in cells:
    cell_list=np.append(cell_list,i['pci'])
cell_list=cell_list.astype(int)

In [23]:
d={}
for i in df2.index:
    c=df2.loc[i]['cell']
    d.update({c['pci']:df2.loc[i]['pos']})

In [24]:
data=pd.DataFrame()

In [25]:
x=np.array([])
for i in df_ue['id']:
    dic=df_ue.loc[i]['cell_info']
    powers={}
    pos=df_ue.loc[i]['pos']
    powers.update({'x':pos[0]})
    powers.update({'y':pos[1]})
    for i in dic:
        powers.update({i['pci']:i['dl_rx_power']})
    x=np.append(x,powers)

In [37]:
data = pd.DataFrame.from_records(x)

In [38]:
data

,x,y,168,169,170,901,902,900,377,376,...,133,320,318,319,250,249,251,774,776,775
0,12.380854,51.339139,-131,-140,-114,-111,-140,-140,-118,-136,...,-95,-113,-123,-97,-133,-135,-106,-112,-99,-87
1,12.378348,51.340952,-137,-137,-108,-106,-135,-135,-107,-129,...,-84,-83,-98,-74,-138,-141,-112,-125,-125,-95
2,12.377739,51.339400,-126,-136,-109,-109,-139,-139,-117,-131,...,-95,-115,-115,-85,-139,-139,-110,-125,-118,-98
3,12.378550,51.338761,-125,-137,-112,-111,-141,-141,-120,-133,...,-97,-121,-121,-91,-137,-137,-108,-123,-109,-99
4,12.380950,51.339520,-132,-140,-113,-110,-140,-140,-117,-136,...,-94,-109,-122,-97,-132,-136,-107,-111,-106,-83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,12.380463,51.340135,-134,-140,-112,-109,-138,-138,-114,-134,...,-89,-102,-118,-95,-133,-137,-109,-115,-115,-85
296,12.381386,51.340308,-136,-141,-113,-109,-138,-138,-114,-136,...,-91,-101,-121,-101,-130,-137,-109,-111,-111,-81
297,12.378390,51.339786,-130,-137,-109,-108,-138,-138,-114,-131,...,-92,-113,-113,-83,-139,-139,-110,-123,-121,-95
298,12.381421,51.339225,-132,-141,-115,-111,-140,-140,-118,-137,...,-96,-112,-124,-99,-131,-135,-106,-108,-95,-83
299,12.380928,51.338149,-127,-141,-116,-113,-142,-142,-123,-138,...,-100,-121,-127,-99,-133,-133,-104,-116,-91,-102

In [39]:
noise=np.power(10,-104/10) #https://www.sciencedirect.com/topics/engineering/noise-power -> 10MHz bandwidth (50PRBs)
sectors=cell_list
cluster=sectors

df2=pd.DataFrame()
#df2=bib.get_int(data,sectors,cluster) #only usefull if NOT all cells are in one cluster

In [43]:
df=df2.copy()

SINR_1_list=np.array([])
SINR_2_list=np.array([])
c_cell=np.array([])
s_cell=np.array([])
for i in np.arange(0, len(df)):
    p_r=df.loc[i,:]
    p_r=p_r[2:2+len(sectors)] #goes through file line by line and selects the line
    p_r=np.power(10, p_r/10) # calculate the linear values for capacity calculations
    p_r=p_r.sort_values(ascending=False) # sort values by their order
    a_r=np.sqrt(p_r) #calculate the amplitude
    index=p_r.index.values #Extract all index values 
    index=index.astype(np.int) #PCIen as integer
    a_r=np.array(a_r)
    p_r=np.array(p_r)
    inter=df.loc[i,'inter']
    pci_coord= index[1]
    SINR_1= p_r[0]/(np.sum(p_r[1:len(p_r)])+noise)
    SINR_2= np.power(np.sum(a_r[0:2]),2)/(np.sum(p_r[2:len(p_r)])+noise)
    #SINR_1= p_r[0]/(np.sum(p_r[1:len(p_r)])+inter+noise) #one bs sending -> rest interference
    #SINR_2= np.power(np.sum(a_r[0:2]),2)/(np.sum(p_r[2:len(p_r)])+inter+noise)
    SINR_1_list=np.append(SINR_1_list,10*np.log10(SINR_1)) #appends the calculated elements
    SINR_2_list=np.append(SINR_2_list,10*np.log10(SINR_2))
    s_cell=np.append(s_cell,index[0])
    c_cell=np.append(c_cell,index[1])

In [44]:
print(SINR_1_list)

[ 4.33169969  6.1803568   7.31918311  2.72182903  8.39627661  0.08668655
  8.96429319  2.41556409  7.3000516   1.41712218  4.2101101  -0.92060472
 17.45598478  1.16636716  0.25585964  9.00523924 12.12890883  6.52342529
  2.50387133 24.57168888 -0.87009573  3.33422841  3.33954516 -0.28755194
  0.90014369  1.53749331  3.23813513  5.38797303  2.59198169  1.41884749
  5.76926469  9.54691661 -1.07089109  0.1865592  -3.0561774  11.55356029
  5.19563144  0.87953122 -0.74202174 -1.99972954  4.60452625  5.92179545
 -2.25427446  5.47548666  4.77727818  0.87858884  5.61800143 13.46806252
  5.33000387 -2.74654076 -1.44458333  9.89108504  5.32517322  4.34243597
 20.50625587  0.10078123 16.92885082  1.36082335  5.48344872 -1.96498304
  3.67843833  4.95073049  0.24159099 -2.57393827 -0.91034306 18.76222945
  9.6870929  -0.17525918  9.38316094 13.35718342 -0.20414302 -2.44295811
  2.0442084   4.27366395  0.7166481   1.10819917  0.11138379 12.67225667
 12.12598585 -2.40107071 -2.46420714  2.98373878  1.35980994  5.93665293
  3.93426481  0.16802562  7.16243831  9.93133828  3.69417149 -1.78786639
 18.09678859 -2.68494024  2.59496525 -2.31676938  4.52067038  8.68350283
 17.03876009  1.57131301 12.65793834 -3.2274937  15.52619553  2.85891596
 13.46062583 14.95491217 -0.69623609  4.26097804  1.29239488  4.94671123
  8.79753358  4.5606239  13.7332773   7.15162875  1.54036961 -1.57356488
 12.8569346   4.2199316   3.89539636  6.98611946 -2.34717257  2.49980802
 -3.04286267  1.38784878 -1.80387914  2.4124983  10.58572337  6.49675023
 11.62690675 -1.07585376  4.76809323 -0.75681144  0.66220323  8.05733788
 14.11117058  5.36375185  3.15728851  7.12397078  2.72418889 14.37658623
  6.49675023  0.52438928  6.75720663  1.36316974 15.09340079 -2.45438682
  3.44790687 -3.83182984  7.87062368  8.29571984 22.54372954 14.37729819
  0.13745487 -1.44782229  6.65965715  2.59300547 -3.39629816  4.905134
 20.16915546 18.14534817  4.60375808  0.77229536  2.10498892  4.65110032
  0.56007713 -0.28945708 -0.86408462  0.57595892  9.75544822 -1.4455983
  2.09847503  4.05836678  3.81571225  3.31044724 -0.92434789 -0.83248287
  2.53534143  7.12397078  6.23745763 -3.1219791  17.28481599  2.79093495
  1.91814667  0.11582017  1.52615188  5.30058158 11.70694583  0.53650758
 12.47056224 -0.14568743 -0.44920623  8.14042755  1.74024618 11.55416384
  5.67591121  5.84561059 -0.2609247   2.25335018 -0.96165776  9.66100855
  4.54049443  4.27366395  2.92079979 18.09587534 -0.38965403  1.52768221
  3.79078207  7.12372941  5.20413797 -2.79624729 15.43657293 -1.70764512
  9.93133828  8.70309053  4.00008979 -1.41417063  5.39195727  0.28458315
  9.35662155 -2.20557574  5.20988222 -1.05723416  3.53379528 13.05470718
 -2.330169   -1.07782165  2.88029244  0.67657314  1.76785697 -0.84165179
  2.54187554 -0.94792869 11.59414314 -0.22586935  3.06082224  3.4726457
 -0.53921956  4.49810842  8.77926187  3.06049256 -3.22777865  2.48482852
  6.348771   -1.43104755  1.3890383   1.76785697  0.85258949  0.99582355
  2.92919671  6.5040645   5.16680288 -2.330169    1.90226146  1.06300397
  3.50243271 -0.28528685  2.06829931  4.4608321  -3.27125996  3.97522221
  3.22475814  6.39604927  8.16238717 10.79443877  2.12371494 10.4339446
  2.38325654  5.92508908  5.90630083  7.77439078 11.27563281  2.23101517
 -2.39902448  2.36674447 14.65627625  3.67268331  7.4474823  -3.32052045
 -1.38194896  4.52792164  1.60354318 11.76033138  0.49645729 17.32475088
 12.83269851  1.66705255  3.46240112  5.76414983  6.63214146  0.49791776
  6.36874601  0.55465982  1.6179904  -0.89264568 -0.494116    2.74602123
 11.99422906  2.62629775  8.7926349   6.76812679  7.9862234   3.1486717 ]

In [24]:
s_cell=s_cell.astype(int)
c_cell=c_cell.astype(int)

In [25]:
df['JT_1 SINR [dB]']=SINR_1_list
df['JT_2 SINR [dB]']=SINR_2_list
df['PCI Serving']=s_cell
df['PCI Coord']=c_cell

In [26]:
df

,x,y,168,169,170,901,902,900,377,376,...,249,251,774,776,775,inter,JT_1 SINR [dB],JT_2 SINR [dB],PCI Serving,PCI Coord
0,12.380854,51.339139,-131,-140,-114,-111,-140,-140,-118,-136,...,-135,-106,-112,-99,-87,6.961083e-10,1.409338,5.395010,775,133
1,12.378348,51.340952,-137,-137,-108,-106,-135,-135,-107,-129,...,-141,-112,-125,-125,-95,9.553407e-09,3.176740,7.131541,319,320
2,12.377739,51.339400,-126,-136,-109,-109,-139,-139,-117,-131,...,-139,-110,-125,-118,-98,5.464377e-10,4.419560,8.212793,319,133
3,12.378550,51.338761,-125,-137,-112,-111,-141,-141,-120,-133,...,-137,-108,-123,-109,-99,3.846301e-10,-0.134847,4.605813,319,133
4,12.380950,51.339520,-132,-140,-113,-110,-140,-140,-117,-136,...,-136,-107,-111,-106,-83,6.852466e-10,5.475245,9.060011,775,133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,12.380463,51.340135,-134,-140,-112,-109,-138,-138,-114,-134,...,-137,-109,-115,-115,-85,1.687499e-09,-0.346754,5.891884,775,133
296,12.381386,51.340308,-136,-141,-113,-109,-138,-138,-114,-136,...,-137,-109,-111,-111,-81,1.009095e-09,5.843846,10.334992,775,133
297,12.378390,51.339786,-130,-137,-109,-108,-138,-138,-114,-131,...,-139,-110,-123,-121,-95,1.015031e-09,3.818989,8.026236,319,133
298,12.381421,51.339225,-132,-141,-115,-111,-140,-140,-118,-137,...,-135,-106,-108,-95,-83,7.570413e-10,5.057074,7.984402,775,776
299,12.380928,51.338149,-127,-141,-116,-113,-142,-142,-123,-138,...,-133,-104,-116,-91,-102,3.448987e-10,0.308175,4.028959,776,319

In [27]:
df1=df

In [30]:
df=pd.DataFrame()
df['x']=df1['x']
df['y']=df1['y']
df['PCI Serving']=df1['PCI Serving']
df['PCI Coord']=df1['PCI Coord']
df['JT_1 SINR [dB]']=df1['JT_1 SINR [dB]']
df['JT_2 SINR [dB]']=df1['JT_2 SINR [dB]']
df['usage']=np.zeros(len(df1))
df['id']=np.arange(0,len(df1))

In [31]:
df

,x,y,PCI Serving,PCI Coord,JT_1 SINR [dB],JT_2 SINR [dB],usage,id
0,12.380854,51.339139,775,133,1.409338,5.395010,0.0,0
1,12.378348,51.340952,319,320,3.176740,7.131541,0.0,1
2,12.377739,51.339400,319,133,4.419560,8.212793,0.0,2
3,12.378550,51.338761,319,133,-0.134847,4.605813,0.0,3
4,12.380950,51.339520,775,133,5.475245,9.060011,0.0,4
...,...,...,...,...,...,...,...,...
295,12.380463,51.340135,775,133,-0.346754,5.891884,0.0,295
296,12.381386,51.340308,775,133,5.843846,10.334992,0.0,296
297,12.378390,51.339786,319,133,3.818989,8.026236,0.0,297
298,12.381421,51.339225,775,776,5.057074,7.984402,0.0,298
299,12.380928,51.338149,776,319,0.308175,4.028959,0.0,299

In [32]:
#check if the number of users (positions) for the serving pci is >10
df_f=df.groupby('PCI Serving')
count=0
for i in df['PCI Serving'].unique():
    k=df_f.get_group(i)
    if(len(k)<10):
        cluster=np.delete(cluster,count) #delete cells with less than 10 positions
        df=df[df['PCI Serving']!=i]
    count+=1

In [33]:
df

,x,y,PCI Serving,PCI Coord,JT_1 SINR [dB],JT_2 SINR [dB],usage,id
0,12.380854,51.339139,775,133,1.409338,5.395010,0.0,0
1,12.378348,51.340952,319,320,3.176740,7.131541,0.0,1
2,12.377739,51.339400,319,133,4.419560,8.212793,0.0,2
3,12.378550,51.338761,319,133,-0.134847,4.605813,0.0,3
4,12.380950,51.339520,775,133,5.475245,9.060011,0.0,4
...,...,...,...,...,...,...,...,...
295,12.380463,51.340135,775,133,-0.346754,5.891884,0.0,295
296,12.381386,51.340308,775,133,5.843846,10.334992,0.0,296
297,12.378390,51.339786,319,133,3.818989,8.026236,0.0,297
298,12.381421,51.339225,775,776,5.057074,7.984402,0.0,298
299,12.380928,51.338149,776,319,0.308175,4.028959,0.0,299

In [34]:
df.to_csv('Prepro/Test-Data')